---
- name: monasca-api | restart | restart monasca-api service
  service: name=monasca-api state=restarted enabled=yes
  when: monasca_api_restart_required

- name: monasca-api | start | start monasca-api service
  service: name=monasca-api state=started enabled=yes

- name: wait for api port
  wait_for: port={{monasca_api_client_port}} host={{monasca_api_bind_host | default('127.0.0.1') }} state=started timeout={{ monasca_wait_for_period }}
  when: verify
